#!/bin/bash
clear
echo -n "Enter the Process Id to be killed : " 
read prid
if [ $prid -le 1 -o $prid -ge 32768 ]
then
echo "Invalid Range of Process Id"  
elif
ps -p $prid > /dev/null 2>&1 
then
kill -9 $prid
echo "Process is killed successfully"
else 
echo "Process with this process Id is not in running state"
fi

